#!/usr/bin/env zsh
# env/paths.zsh — env-tier PATH configuration.
#
# Sourced from init_env.zsh (which is sourced from .zshenv) on EVERY zsh
# invocation. Per the env-tier contract (rev. 6 of zsh_init_plan.md §3, §5):
#   - Fast: target p50 < 10ms, p95 < 20ms, hard fail at 50ms.
#   - Silent: no stdout. Stderr only on the 14-day staleness nag.
#   - No shellouts. Brew prefixes are hardcoded (regenerated by
#     `make refresh-paths`). zstat (zsh builtin) is used for the
#     freshness check — no `stat` shellout, no `find -newer` walk.
#   - Idempotent re-sourcing: `_path_prepend` de-dups.

# ──────────────────────────────────────────────────────────────────────
# _path_prepend <dir>
#   Prepend $1 to PATH iff (a) $1 is a directory and (b) not already on PATH.
#   Replaces the old _prepend_brew_path helper, which shelled out to
#   `brew --prefix` on every PATH-dependent command.
# ──────────────────────────────────────────────────────────────────────
_path_prepend() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  case ":$PATH:" in
    *":$dir:"*) return 0 ;;
    *) export PATH="$dir:$PATH" ;;
  esac
}

# Homebrew itself (always-on prefix, no resolution needed).
_path_prepend "/opt/homebrew/bin"

# >>> generated by `make refresh-paths` — do not edit by hand >>>
# Last refreshed: 2026-05-01
# Source: brew --prefix output for the six tracked formulas.
# Stale-after: 14 days (env-tier nag below; brew() wrapper in rc/functions.zsh
# auto-fires `make refresh-paths` on common path-affecting subcommands).
typeset -gA _BREW_PREFIX
_BREW_PREFIX=(
  coreutils "/opt/homebrew/opt/coreutils"
  grep "/opt/homebrew/opt/grep"
  gnu-sed "/opt/homebrew/opt/gnu-sed"
  gawk "/opt/homebrew/opt/gawk"
  findutils "/opt/homebrew/opt/findutils"
  postgresql "/opt/homebrew/opt/postgresql@17"
)
# <<< end generated block <<<

# Prepend GNU coreutils/grep/sed/awk/findutils gnubin dirs.
# _path_prepend gates on `[[ -d ]]`, so a stale prefix (after `brew uninstall`)
# is silently skipped — never PATH corruption.
_path_prepend "${_BREW_PREFIX[coreutils]}/libexec/gnubin"
_path_prepend "${_BREW_PREFIX[grep]}/libexec/gnubin"
_path_prepend "${_BREW_PREFIX[gnu - sed]}/libexec/gnubin"
_path_prepend "${_BREW_PREFIX[gawk]}/libexec/gnubin"
_path_prepend "${_BREW_PREFIX[findutils]}/libexec/gnubin"

# PostgreSQL — versioned formula (keg-only). The generated _BREW_PREFIX entry
# carries the active version on this machine. The fallback chain (postgresql@17
# → postgresql@14 → postgresql) is preserved by `make refresh-paths`'s
# probe order; if the active version changes, regenerate the block.
_path_prepend "${_BREW_PREFIX[postgresql]}/bin"

# User-local installs (pipx, Cursor Agent, etc.). Placed BEFORE Homebrew bin
# above? No — _path_prepend prepends, so the order in this file = the order on
# PATH (last-prepended wins / appears first). The intent (preserved from the
# original paths.sh) is: $HOME/bin > $HOME/go/bin > $HOME/.local/bin > brew >
# system. We achieve this by prepending in increasing-priority order below.
_path_prepend "$HOME/.local/bin"

# Go packages (installed via `go install`).
_path_prepend "$HOME/go/bin"

# LM Studio CLI — was previously appended via .zshrc, moved here so it lands
# in env-tier and survives non-interactive shells. _path_prepend de-dups
# against any stale .zshrc append the LM Studio installer might re-add.
_path_prepend "$HOME/.lmstudio/bin"

# User bin — last prepend so it ends up first on PATH (highest precedence,
# matches the original paths.sh contract).
_path_prepend "$HOME/bin"

# ──────────────────────────────────────────────────────────────────────
# 14-day staleness nag (rev. 5/6 §5 backstop).
#
# The brew() wrapper in rc/functions.zsh auto-fires `make refresh-paths` on
# install/upgrade/uninstall/reinstall/bundle/update — the common interactive
# path. This nag catches the cases the wrapper misses: background brew auto-
# update, Brewfile invocations from mac_setup/ scripts, agent-driven non-
# interactive `brew install`, idle machines, brand-new clones. One stderr
# line at most every 14 days; uses zstat builtin (no shellout); cost < 1ms.
#
# Does NOT auto-run `make refresh-paths` from env-tier — that would re-
# introduce brew --prefix shellouts and surprise users with diffs during
# routine `zsh -c '<one-liner>'` invocations.
# ──────────────────────────────────────────────────────────────────────
_paths_check_freshness() {
  local sentinel="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/paths-refreshed"
  local age_days_threshold=14
  if [[ ! -f "$sentinel" ]]; then
    printf 'note: ~/code/scripts shell paths never refreshed; run: make -C ~/code/scripts refresh-paths\n' >&2
    return 0
  fi
  # zmodload zsh/stat exposes the zstat builtin (no `stat` shellout).
  zmodload -F zsh/stat b:zstat 2>/dev/null || return 0
  local mtime
  zstat -A mtime +mtime "$sentinel" 2>/dev/null || return 0
  local now=$EPOCHSECONDS
  local age_days=$(((now - mtime) / 86400))
  ((age_days < age_days_threshold)) && return 0
  printf 'note: ~/code/scripts brew paths last refreshed %d days ago; consider: make -C ~/code/scripts refresh-paths\n' "$age_days" >&2
}
_paths_check_freshness
