#!/usr/bin/env bats
# Tests for the `make refresh-paths` target in the scripts repo Makefile.
#
# The target regenerates the `_BREW_PREFIX=( … )` block in
# shell/env/paths.zsh from current `brew --prefix` output and touches the
# freshness sentinel that the env-tier nag in paths.zsh checks. These
# tests exercise the contract without mutating the real repo:
#   - missing brew → exit 3 (per docs/EXIT-CODES.md)
#   - regenerated block preserves the >>> / <<< markers
#   - all six tracked keys present (coreutils, grep, gnused, gawk,
#     findutils, postgresql)
#   - file mode preserved across regen
#   - second run is byte-identical to first (idempotent except date line)
#   - sentinel file is touched

setup() {
  load 'test_helper/bats-support/load'
  load 'test_helper/bats-assert/load'
  REPO="$(cd "$BATS_TEST_DIRNAME/.." && pwd -P)"

  # Build a self-contained sandbox repo containing only the files the
  # refresh-paths target reads/writes: the Makefile target itself and a
  # minimal shell/env/paths.zsh with the marker block.
  SANDBOX="$(mktemp -d)"
  mkdir -p "$SANDBOX/shell/env"

  # Copy ONLY the refresh-paths target into a stub Makefile so we don't
  # accidentally invoke other targets (lint, test, etc.) that need the
  # full project tree. The recipe is self-contained.
  awk '
    /^# --- refresh-paths/, /^clean: ##/ {
      if ($0 ~ /^clean: ##/) exit
      print
    }
  ' "$REPO/Makefile" >"$SANDBOX/Makefile.snippet"
  {
    echo ".PHONY: refresh-paths"
    cat "$SANDBOX/Makefile.snippet"
  } >"$SANDBOX/Makefile"

  # Minimal paths.zsh with just the marker block and a couple of
  # _path_prepend calls referencing _BREW_PREFIX keys (so the file is
  # plausibly representative). The body around the markers is opaque to
  # refresh-paths — it edits ONLY the lines between the markers.
  cat >"$SANDBOX/shell/env/paths.zsh" <<'EOF'
# fixture paths.zsh
# >>> generated by `make refresh-paths` — do not edit by hand >>>
# Last refreshed: 1970-01-01
# Source: brew --prefix output for the six tracked formulas.
# Stale-after: 14 days (env-tier nag below; brew() wrapper in rc/functions.zsh
# auto-fires `make refresh-paths` on common path-affecting subcommands).
typeset -gA _BREW_PREFIX
_BREW_PREFIX=(
  coreutils "/old/coreutils"
  grep "/old/grep"
  gnused "/old/gnu-sed"
  gawk "/old/gawk"
  findutils "/old/findutils"
  postgresql "/old/postgresql@1"
)
# <<< end generated block <<<
_path_prepend "${_BREW_PREFIX[coreutils]}/libexec/gnubin"
EOF
  chmod 755 "$SANDBOX/shell/env/paths.zsh"

  # Each test gets its own sentinel cache root.
  export XDG_CACHE_HOME="$SANDBOX/.cache"
}

teardown() {
  rm -rf "$SANDBOX"
}

@test "refresh-paths: missing brew exits non-zero with hint" {
  # Stub PATH so brew is not findable. /usr/bin:/bin keeps make/awk/etc.
  # Note: make wraps the recipe's exit 3 in its own non-zero exit; we
  # assert the failure mode via stderr message rather than exact code.
  PATH="/usr/bin:/bin" run make -C "$SANDBOX" refresh-paths
  assert_failure
  assert_output --partial "brew not installed"
}

@test "refresh-paths: regenerated block preserves >>> and <<< markers" {
  command -v brew >/dev/null 2>&1 || skip "brew not installed on this runner"
  run make -C "$SANDBOX" refresh-paths
  assert_success
  run grep -c '^# >>> generated by `make refresh-paths`' "$SANDBOX/shell/env/paths.zsh"
  assert_output "1"
  run grep -c '^# <<< end generated block <<<' "$SANDBOX/shell/env/paths.zsh"
  assert_output "1"
}

@test "refresh-paths: all six tracked keys present after regen" {
  command -v brew >/dev/null 2>&1 || skip "brew not installed on this runner"
  run make -C "$SANDBOX" refresh-paths
  assert_success
  for key in coreutils grep gnused gawk findutils postgresql; do
    run grep -E "^  $key \"" "$SANDBOX/shell/env/paths.zsh"
    assert_success
  done
}

@test "refresh-paths: 'Last refreshed' date is updated to today" {
  command -v brew >/dev/null 2>&1 || skip "brew not installed on this runner"
  today="$(date +%Y-%m-%d)"
  run make -C "$SANDBOX" refresh-paths
  assert_success
  run grep -F "# Last refreshed: $today" "$SANDBOX/shell/env/paths.zsh"
  assert_success
}

@test "refresh-paths: file mode preserved across regen" {
  command -v brew >/dev/null 2>&1 || skip "brew not installed on this runner"
  # Use a portable stat invocation: GNU `stat -c` works on Linux and on
  # macOS when coreutils is on PATH (which is the case in this repo's
  # env-tier; tests inherit that PATH). BSD `stat -f` is used as a
  # fallback for plain macOS without coreutils.
  _mode() {
    stat -c '%a' "$1" 2>/dev/null || stat -f '%Lp' "$1"
  }
  before="$(_mode "$SANDBOX/shell/env/paths.zsh")"
  run make -C "$SANDBOX" refresh-paths
  assert_success
  after="$(_mode "$SANDBOX/shell/env/paths.zsh")"
  [ "$before" = "$after" ]
}

@test "refresh-paths: second run produces byte-identical paths.zsh" {
  command -v brew >/dev/null 2>&1 || skip "brew not installed on this runner"
  # First run brings the file to current-truth state.
  run make -C "$SANDBOX" refresh-paths
  assert_success
  cp "$SANDBOX/shell/env/paths.zsh" "$SANDBOX/paths.zsh.snapshot"
  # Second run on the same day must be a no-op (cmp returns 0).
  run make -C "$SANDBOX" refresh-paths
  assert_success
  run cmp -s "$SANDBOX/shell/env/paths.zsh" "$SANDBOX/paths.zsh.snapshot"
  assert_success
}

@test "refresh-paths: idempotent re-run prints 'already up to date'" {
  command -v brew >/dev/null 2>&1 || skip "brew not installed on this runner"
  run make -C "$SANDBOX" refresh-paths
  assert_success
  run make -C "$SANDBOX" refresh-paths
  assert_success
  assert_output --partial "already up to date"
}

@test "refresh-paths: freshness sentinel is created/touched" {
  command -v brew >/dev/null 2>&1 || skip "brew not installed on this runner"
  sentinel="$XDG_CACHE_HOME/zsh/paths-refreshed"
  [ ! -e "$sentinel" ]
  run make -C "$SANDBOX" refresh-paths
  assert_success
  [ -f "$sentinel" ]
}

@test "refresh-paths: only mutates content between the markers" {
  command -v brew >/dev/null 2>&1 || skip "brew not installed on this runner"
  # Add a sentinel line immediately BEFORE the >>> marker and immediately
  # AFTER the <<< marker. The recipe must not touch them.
  before_line='# SENTINEL_BEFORE_BLOCK'
  after_line='# SENTINEL_AFTER_BLOCK'
  awk -v b="$before_line" -v a="$after_line" '
    /^# >>> generated/ && !done_b { print b; print; done_b=1; next }
    /^# <<< end generated/ && !done_a { print; print a; done_a=1; next }
    { print }
  ' "$SANDBOX/shell/env/paths.zsh" >"$SANDBOX/shell/env/paths.zsh.tmp"
  mv "$SANDBOX/shell/env/paths.zsh.tmp" "$SANDBOX/shell/env/paths.zsh"
  chmod 755 "$SANDBOX/shell/env/paths.zsh"

  run make -C "$SANDBOX" refresh-paths
  assert_success
  run grep -c "$before_line" "$SANDBOX/shell/env/paths.zsh"
  assert_output "1"
  run grep -c "$after_line" "$SANDBOX/shell/env/paths.zsh"
  assert_output "1"
}
